### ISSUE TITLE
Indentation, linebreaks and comments

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/pepperModules-PAULAModules#4]
The PAULA exporter produces files with only one line, i.e. with no line breaks between elements. This is tough to read and effectively means indentation must be run on the output. It would be great if linebreaking and indentation could be run on the output automatically.

Also, there are no comments in the different files giving the text of the covered token range. At a minimum, it would be helpful to output the covered token text as a comment in the _tok.xml file.

**Comment by FlorianZipser** [comment]
This issue will be partly fixed in release 1.1.7. The output will than optionally contain comments by setting the customization property 'humanReadable' to 'true'. Since that computation will slow down the export, it is disabled by default. 
The two other points are moved to a new issue #5.
